Feature/change form success behavior
fostyler/fos-flagship pull request #10
Opened 2023-06-26 15:06 UTC by codex-scribe

Have implemented the 3 changes above.
@LailaAli @LailaAli

2023-06-28 16:48 UTC, fostyler requested changes
Hey @codex-scribe just a few clean-up tasks here.

2023-06-28 16:48 UTC, fostyler commented on src/components/ContactForm/index.js
> +          console.log(formRef.current)
Please remove console logs

2023-06-28 16:48 UTC, fostyler commented on src/components/ContactForm/index.js
> +              {errors.map((error, i) => <p className="errorBoxText messageFont" key={i}>{error}</p>)}
You wouldn't want to use just a number for a key, add a relevant string to it

```
key={`errors-${i}`}
```

2023-06-30 18:40 UTC, codex-scribe commented on src/components/ContactForm/index.js
> +          console.log(formRef.current)
Done.

2023-06-30 18:40 UTC, codex-scribe commented on src/components/ContactForm/index.js
> +              {errors.map((error, i) => <p className="errorBoxText messageFont" key={i}>{error}</p>)}
Done.

2023-07-05 16:33 UTC, fostyler approved these changes

2023-07-05 16:33 UTC, merged